project:
  type: book
  output-dir: docs
book:
  title: "Análise Exploratória Multivariada - Tarefas"
  author: "Ana Caroline Alexandre Pantoja"
  date: last-modified
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
  chapters:
    - index.qmd
    - ACP.qmd
    - tarefa3_AF.qmd
format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc-title: "Sumário"
    page-layout: full

editor: visual


